<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <name>JingWei Apps - Kernel</name>
    <artifactId>jingwei-apps-kernel</artifactId>
    <description>精卫平台的应用核心模块，其负责加载应用，并为应用提供基础的运行支持</description>

    <parent>
        <groupId>io.crazydan.jingwei</groupId>
        <artifactId>jingwei-apps</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <properties>
    </properties>

    <dependencies>
    </dependencies>

    <build>
        <plugins>
            <!-- Note：该插件的配置见 io.github.entropy-cloud:nop-entropy -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
