<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <name>JingWei UI Schema</name>
    <artifactId>jingwei-ui-schema</artifactId>
    <packaging>pom</packaging>

    <parent>
        <groupId>io.crazydan.jingwei</groupId>
        <artifactId>jingwei-ui</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <modules>
        <!-- Note: codegen 需在 model 之前构建，从而确保最新生成的代码能够被构建到 model 中 -->
        <module>codegen</module>

        <module>xdefs</module>
        <module>model</module>
    </modules>

    <properties>
    </properties>

    <dependencies>
    </dependencies>
</project>
