<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <name>JingWei</name>
    <groupId>io.crazydan.jingwei</groupId>
    <artifactId>jingwei-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <description>精卫（JingWei）—— 个人数字资产平台</description>
    <url>https://jingwei.crazydan.io</url>

    <parent>
        <groupId>io.crazydan.duzhou.framework</groupId>
        <artifactId>parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <modules>
        <!-- Note: 模块声明顺序会影响构建顺序 -->
        <module>100.app</module>
        <module>600.apps</module>

        <module>080.starter</module>

        <module>800.tools</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>io.crazydan.duzhou.framework</groupId>
            <artifactId>duzhou-autotest</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <jingwei.version>0.1.0-SNAPSHOT</jingwei.version>
        <nop-extensions.version>1.0.0-SNAPSHOT</nop-extensions.version>
    </properties>

    <licenses>
        <license>
            <name>GNU Lesser General Public License v3.0</name>
            <url>https://www.gnu.org/licenses/lgpl-3.0.en.html</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>flytreeleft</name>
            <email>flytreeleft@crazydan.org</email>
            <organization>Crazydan Studio</organization>
            <organizationUrl>https://studio.crazydan.org</organizationUrl>
        </developer>
    </developers>

    <issueManagement>
        <system>Github</system>
        <url>https://github.com/crazydan-studio/jingwei/issues</url>
    </issueManagement>
    <scm>
        <connection>scm:git:git://github.com/crazydan-studio/jingwei.git</connection>
        <developerConnection>scm:git:ssh://github.com:crazydan-studio/jingwei.git</developerConnection>
        <url>http://github.com/crazydan-studio/jingwei/tree/master</url>
    </scm>

    <repositories>
        <repository>
            <id>nop-repo</id>
            <url>https://repo.nop.crazydan.io/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>nop-repo</id>
            <url>https://repo.nop.crazydan.io/</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencyManagement>
        <dependencies>
            <!-- 本项目子模块，便于其他项目引入 -->
            <dependency>
                <groupId>io.crazydan.jingwei</groupId>
                <artifactId>jingwei-app-schema</artifactId>
                <version>${jingwei.version}</version>
            </dependency>
            <dependency>
                <groupId>io.crazydan.jingwei</groupId>
                <artifactId>jingwei-app-model</artifactId>
                <version>${jingwei.version}</version>
            </dependency>
            <dependency>
                <groupId>io.crazydan.jingwei</groupId>
                <artifactId>jingwei-app-coder</artifactId>
                <version>${jingwei.version}</version>
            </dependency>
            <dependency>
                <groupId>io.crazydan.jingwei</groupId>
                <artifactId>jingwei-app-service</artifactId>
                <version>${jingwei.version}</version>
            </dependency>

            <dependency>
                <groupId>io.crazydan.jingwei</groupId>
                <artifactId>jingwei-apps-graphiql</artifactId>
                <version>${jingwei.version}</version>
            </dependency>
            <dependency>
                <groupId>io.crazydan.jingwei</groupId>
                <artifactId>jingwei-apps-kernel</artifactId>
                <version>${jingwei.version}</version>
            </dependency>
            <dependency>
                <groupId>io.crazydan.jingwei</groupId>
                <artifactId>jingwei-apps-portal</artifactId>
                <version>${jingwei.version}</version>
            </dependency>
            <!-- End -->

            <dependency>
                <groupId>io.github.entropy-cloud.extensions</groupId>
                <artifactId>nop-undertow-starter</artifactId>
                <version>${nop-extensions.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>*.yaml</include>
                    <include>*.yml</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>*.yaml</exclude>
                    <exclude>*.yml</exclude>
                </excludes>
            </resource>
        </resources>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>*.yaml</include>
                    <include>*.yml</include>
                </includes>
            </testResource>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>*.yaml</exclude>
                    <exclude>*.yml</exclude>
                </excludes>
            </testResource>
        </testResources>
    </build>
</project>
