<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <name>JingWei Starter</name>
    <artifactId>jingwei-starter</artifactId>
    <description>精卫平台的 Web 服务启动器，其将被打包为最终的可执行 jar 包</description>

    <parent>
        <groupId>io.crazydan.jingwei</groupId>
        <artifactId>jingwei-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <properties>
        <maven.install.skip>true</maven.install.skip>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.entropy-cloud.extensions</groupId>
            <artifactId>nop-undertow-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>io.crazydan.jingwei</groupId>
            <artifactId>jingwei-apps-portal</artifactId>
        </dependency>
        <dependency>
            <groupId>io.crazydan.jingwei</groupId>
            <artifactId>jingwei-app-service</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.entropy-cloud</groupId>
            <artifactId>nop-biz-file-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.entropy-cloud</groupId>
            <artifactId>nop-integration-file-local</artifactId>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Note：该插件的配置见 io.github.entropy-cloud:nop-entropy -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <!-- 可执行 jar 打包: https://maven.apache.org/plugins/maven-shade-plugin/examples/executable-jar.html -->
                <!--
                注意，该插件会把依赖全部解包并合并放在可执行的 jar 中，
                即 uberjar 打包模式，其比 Spring boot 的 nested-jars 打包模式的加载速度会更快一点，
                但是，同名类和资源文件会出现被覆盖的问题，因此，需尽量避免同名文件，
                或者通过该插件的 transformer 对同名文件做合并（https://juejin.cn/post/7065862239349112863）。
                在依赖较复杂，且可能存在多版本时，可以尝试采用插件 spring-boot-maven-plugin
                以 nested-jars 模式打包
                -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>3.1.1</version>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>shade</goal>
                            </goals>
                            <configuration>
                                <finalName>${project.build.finalName}-exec</finalName>
                                <transformers>
                                    <transformer
                                            implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                        <mainClass>io.crazydan.jingwei.JingWeiStarter</mainClass>
                                    </transformer>
                                    <!--
                                    META-INF/services/ 中会存在同名文件，需将其内容合并，以确保
                                    Nop IocCoreInitializer 等能够被 ServiceLoader 加载:
                                    https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer
                                    -->
                                    <transformer
                                            implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                </transformers>
                                <!--
                                修复运行 jar 时出现 "java.lang.SecurityException: Invalid signature file digest for Manifest main attributes" 异常的问题:
                                https://stackoverflow.com/questions/34855649/invalid-signature-file-digest-for-manifest-main-attributes-exception-while-tryin#answer-64263739
                                -->
                                <filters>
                                    <filter>
                                        <artifact>*:*</artifact>
                                        <excludes>
                                            <exclude>META-INF/*.SF</exclude>
                                            <exclude>META-INF/*.DSA</exclude>
                                            <exclude>META-INF/*.RSA</exclude>
                                        </excludes>
                                    </filter>
                                </filters>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
