# Nop平台自身会加载application.yaml配置文件，与Spring和Quarkus框架可以共享配置文件

nop:
  debug: true

  orm:
    init-database-schema: true
    enable-tenant-by-default: false
    auto-add-tenant-col: false

  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc-url: jdbc:mysql://127.0.0.1:3306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    # username: nop
    # password: nop-test
    metrics-enabled: true
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:${project.basedir}/_data/local
    username: sa
    password:

  gateway:
    http-filter:
      enabled: true

  file:
    #store-impl: oss
    store-dir: ${project.basedir}/_data/files

  extension:
    undertow:
      server:
        port: 8181
        static-dir: ${jingwei.app.static-dir}
        compression:
          enabled: true
          # min-response-size: 2048
          mime-types: text/html,text/xml,text/plain,text/javascript,text/css,application/json,application/xml,application/javascript,application/x-shockwave-flash

  vfs:
    custom:
      ns-mappings: |
        app-install-dir:${jingwei.app.install-dir},
        app-static-dir:${jingwei.app.static-dir}
  ai:
    # 在该目录中以 `{llmName}.txt` 形式按模型名创建文本文件并在其中放置 API Key
    secret-dir: ${project.basedir}/_data/ai/secret
    service:
      # LLM 引擎执行时是否自动打印所有请求和响应消息
      log-message: true
      # LLM 引擎采用 mock 方式执行时所使用的输入输出目录
      mock-dir: ${project.basedir}/_data/ai/mock
      # 是否启用系统提示词
      enable-work-mode-system-prompt: true

jingwei:
  app:
    static-dir: ${project.basedir}/_data/app-pages
    install-dir: ${project.basedir}/_data/app-installed
